/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ticketSol from "./Ticket.sol";
export type { ticketSol };
export type { Administration } from "./Administration";
export type { Forwarder } from "./Forwarder";
export type { MintManager } from "./MintManager";
