/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interactHenkakuTokenSol from "./InteractHenkakuToken.sol";
export type { interactHenkakuTokenSol };
import type * as external from "./external";
export type { external };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Nengajo } from "./Nengajo";
export type { Omamori } from "./Omamori";
